/**
 * app/api/local-config/route.ts
 * Read / write / export the local bootstrap config.
 *
 *   GET  /api/local-config             — return current config (admin-only),
 *                                        with passwordHash / salt / sessionSecret masked
 *   GET  /api/local-config?export=env  — download a generated .env.local file
 *   POST /api/local-config             — merge { admin?, firebase?, cloudinary?, serviceAccountJson? }
 *
 * Auth: requires the `tc-admin` cookie (matches middleware).
 */

import { NextRequest, NextResponse } from 'next/server';
import {
  readLocalConfig,
  writeLocalConfig,
  LocalConfig,
  LocalFirebase,
  LocalCloudinary,
  LocalAdmin,
} from '@/lib/localConfig';

function unauthorized(): NextResponse {
  return NextResponse.json({ ok: false, error: 'unauthorized' }, { status: 401 });
}

function requireAdmin(req: NextRequest): boolean {
  return !!req.cookies.get('tc-admin')?.value;
}

// ─── Mask sensitive fields when echoing config back to the browser ──────

function maskConfig(cfg: LocalConfig): Omit<LocalConfig, 'sessionSecret'> & {
  admin?: Omit<LocalAdmin, 'passwordHash' | 'salt'>;
} {
  // sessionSecret intentionally omitted entirely.
  const { sessionSecret: _sessionSecret, admin, ...rest } = cfg;
  void _sessionSecret;
  return {
    ...rest,
    admin: admin
      ? {
          email:     admin.email,
          name:      admin.name,
          createdAt: admin.createdAt,
        }
      : undefined,
  };
}

// ─── .env exporter ──────────────────────────────────────────────────────

function buildEnvFile(cfg: LocalConfig): string {
  const fb = cfg.firebase ?? {};
  const cl = cfg.cloudinary ?? {};
  const lines = [
    '# Generated by TradeCircle Firebase Setup Wizard',
    `# ${new Date().toISOString()}`,
    '',
    '# ── Firebase (public, client-side) ────────────────────────────',
    `NEXT_PUBLIC_FIREBASE_API_KEY=${fb.apiKey ?? ''}`,
    `NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${fb.authDomain ?? ''}`,
    `NEXT_PUBLIC_FIREBASE_PROJECT_ID=${fb.projectId ?? ''}`,
    `NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${fb.storageBucket ?? ''}`,
    `NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${fb.messagingSenderId ?? ''}`,
    `NEXT_PUBLIC_FIREBASE_APP_ID=${fb.appId ?? ''}`,
    `NEXT_PUBLIC_FIREBASE_VAPID_KEY=${fb.vapidKey ?? ''}`,
    '',
    '# ── Firebase Admin (server-side, secret) ─────────────────────',
  ];
  if (cfg.serviceAccountJson) {
    // Wrap the JSON in single quotes; escape any internal single quotes.
    const escaped = cfg.serviceAccountJson.replace(/'/g, "'\\''");
    lines.push(`FIREBASE_SERVICE_ACCOUNT_JSON='${escaped}'`);
  } else {
    lines.push('# FIREBASE_SERVICE_ACCOUNT_JSON=');
  }
  lines.push(
    '',
    '# ── Cloudinary (optional) ────────────────────────────────────',
    `NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=${cl.cloudName ?? ''}`,
    `NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET=${cl.uploadPreset ?? ''}`,
    '',
  );
  return lines.join('\n');
}

// ─── Handlers ───────────────────────────────────────────────────────────

export async function GET(req: NextRequest): Promise<NextResponse> {
  if (!requireAdmin(req)) return unauthorized();

  const cfg = await readLocalConfig();
  if (!cfg) {
    return NextResponse.json({ ok: false, error: 'no_config' }, { status: 404 });
  }

  // ?export=env → download
  const exportMode = req.nextUrl.searchParams.get('export');
  if (exportMode === 'env') {
    const env = buildEnvFile(cfg);
    return new NextResponse(env, {
      status:  200,
      headers: {
        'Content-Type':        'text/plain; charset=utf-8',
        'Content-Disposition': 'attachment; filename=".env.local"',
      },
    });
  }

  return NextResponse.json({ ok: true, config: maskConfig(cfg) });
}

export async function POST(req: NextRequest): Promise<NextResponse> {
  if (!requireAdmin(req)) return unauthorized();

  let body: {
    admin?:              Partial<LocalAdmin>;
    firebase?:           LocalFirebase;
    cloudinary?:         LocalCloudinary;
    serviceAccountJson?: string;
  };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ ok: false, error: 'invalid_body' }, { status: 400 });
  }

  // We deliberately do NOT allow callers to overwrite passwordHash/salt
  // here — admin password changes should go through a dedicated endpoint.
  const patch: Partial<LocalConfig> = {};
  if (body.firebase)              patch.firebase           = body.firebase;
  if (body.cloudinary)            patch.cloudinary         = body.cloudinary;
  if (body.serviceAccountJson !== undefined) patch.serviceAccountJson = body.serviceAccountJson;

  const next = await writeLocalConfig(patch);
  return NextResponse.json({ ok: true, config: maskConfig(next) });
}
